# permissions for end users to edit databasebackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: databasebackup-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: my-operator
    app.kubernetes.io/part-of: my-operator
    app.kubernetes.io/managed-by: kustomize
  name: databasebackup-editor-role
rules:
- apiGroups:
  - databases.test.io
  resources:
  - databasebackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databases.test.io
  resources:
  - databasebackups/status
  verbs:
  - get
