---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - databases.test.io
  resources:
  - databasebackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databases.test.io
  resources:
  - databasebackups/status
  verbs:
  - get
  - patch
  - update
