apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-operator-manager-rolebinding
subjects:
  - kind: ServiceAccount
    name: my-operator-controller-manager
    namespace: my-operator-system
roleRef:
  kind: ClusterRole
  name: my-operator-manager-role
  apiGroup: rbac.authorization.k8s.io
